### ISSUE TITLE
When installed with Forestry and JEI causes a weird GUI issue

### ISSUE THREAD

**Issue by Peach774** [RootsTeam/Goetia#10]
This mod when combined with Forestry causes a GUI weirdness when looking through JEI.
![2016-11-05_19 36 28](https://cloud.githubusercontent.com/assets/5171184/20234839/d5ade772-a850-11e6-9491-c7fcbfbad4ac.png)
![2016-11-05_17 42 43](https://cloud.githubusercontent.com/assets/5171184/20234841/d7b922de-a850-11e6-99d1-18662ee971ac.png)

**Comment by werty1124** [comment]
Fixed

**Comment by DeGariless** [comment]
https://github.com/elytra/Unabridged/issues/563
Still having the same issue in 0.3.2

**Comment by Peach774** [comment]
it is tied to forestry somehow

**Comment by mezz** [comment]
Is there a commit where this is fixed? Github shows the last change as 15 days ago, while you said it was fixed 5 days ago.

**Comment by Peach774** [comment]
I dont think there is, which may explain why it isnt fixed. Is there a way to reopen the issue?

**Comment by belathus** [comment]
Yeah, I'm still experiencing this issue as well.

**Comment by ShadowGamerXY** [comment]
Now it should be fixed for real.

**Comment by DeGariless** [comment]
FoReal(tm) :)
